Fix svg size decoder
go-pdf/fpdf pull request #66
Opened 2024-04-04 06:22 UTC by thierry-f-78

Hi, this PR contains contains some improvement to handle SVG as path source for PDF:
- fix a bug about units in width and height of th SVG
- support basic rect form
- support drawing forms with DrawPath() (to fill the form with a color)

2024-04-05 17:22 UTC, sbinet requested changes
thanks for the PR.

could you address the comments from `staticcheck` ?

```
Error: svgbasic.go:230:52: 'bitSize' argument is invalid, must be either 32 or 64 (SA1030)
Error: svgbasic.go:306:4: this value of err is never used (SA4006)
Error: svgbasic.go:306:10: Errorf doesn't have side effects and its return value is ignored (SA4017)
```

also, could you perhaps add a test or example for this new API ?

thanks again.

2024-04-05 21:22 UTC, thierry-f-78 commented
Hi, static check is fixed. I wrote examples asap.

2024-04-06 13:45 UTC, thierry-f-78 commented
example done.

2024-04-09 09:17 UTC, sbinet commented on svgbasic.go
> +// to apply to each position or distance value.
```suggestion
// parseFloatWithUnit parses a float and its unit, e.g. "42pt".
//
// The result is converted into pt values wich is the default document unit.
// parseFloatWithUnit returns the factor to apply to positions or distances to
// convert their values in point units.
```

2024-04-09 09:17 UTC, sbinet commented on svgbasic.go
> +	}
Go "good practices" recommend to use a `switch`.
```suggestion
	switch {
	case strings.HasSuffix(val, "pt"):
		removeUnitChar = 2
		adjustToPt = 1.0
	case strings.HasSuffix(val, "in"):
		removeUnitChar = 2
		adjustToPt = 72.0
	case strings.HasSuffix(val, "mm"):
		removeUnitChar = 2
		adjustToPt = 72.0 / 25.4
	case strings.HasSuffix(val, "cm"):
		removeUnitChar = 2
		adjustToPt = 72.0 / 2.54
	case strings.HasSuffix(val, "pc"):
		removeUnitChar = 2
		adjustToPt = 12.0
	default: // default is pixel
		removeUnitChar = 0
		adjustToPt = 1.0 / 96.0
	}
```

perhaps also add a case for `"px"` pixel units ?

2024-04-09 09:17 UTC, sbinet commented on svgwrite.go
> +// unit of measure specified in New(). If scale its 0, automatically adapt SVG
```suggestion
// unit of measure specified in New(). If scale is 0, SVGBasicWrite automatically adapts the SVG document
```

2024-04-09 09:17 UTC, sbinet commented on svgwrite.go
> +		scale = 1.0 / f.k
could `f.k` be 0 itself ?

2024-04-09 09:17 UTC, sbinet commented on svgwrite.go
> +// as path, so each path can be filled.
```suggestion
// SVGBasicDraw renders the paths in the provided SVGBasicType, but each SVG shape is written
// as a path that can be filled.
```

2024-04-09 09:17 UTC, sbinet commented on svgwrite.go
> +		scale = 1.0 / f.k
could `f.k` be 0 itself ?

2024-04-10 11:15 UTC, thierry-f-78 commented on svgwrite.go
> +		scale = 1.0 / f.k
No, in the fpdf.go file, the function which init doc "fpdfNew()" executes this (fpdf.go, line 126)

```go
 126    switch unitStr {
 127    case "pt", "point":
 128       f.k = 1.0
 129    case "mm":
 130       f.k = 72.0 / 25.4
 131    case "cm":
 132       f.k = 72.0 / 2.54
 133    case "in", "inch":
 134       f.k = 72.0
 135    default:
 136       f.err = fmt.Errorf("incorrect unit %s", unitStr)
 137       return
 138    }

```

So, `f.k` is set, or the fpdfNew() returns an error. 

however, the library may be initialized in the wrong way (eg: `f = &Fpdf{}`). In this case, `f.k` will be 0, but nothing will work anyway. I think a panic is acceptable in this situation.

2024-04-10 11:19 UTC, thierry-f-78 commented on svgwrite.go
> +		scale = 1.0 / f.k
see below, same explanation.

2024-04-10 11:32 UTC, sbinet approved these changes
LGTM

thanks for the PR (and sticking with the somewhat lengthy review)

2024-04-10 11:35 UTC, thierry-f-78 commented
Thank for the code review and for maintaining this libray.

2024-04-10 11:44 UTC, merged